remote_theme: pages-themes/slate@v0.2.0

title: Mon blog
description: Divers sujets techniques
github:
  is_project_page: false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
plugins:
- jekyll-remote-theme
