remote_theme: pages-themes/slate@v0.2.0

title: Le blog du Tigre
description: Divers sujets techniques et philosophiques qui m'interressent
lang: fr_FR
github:
  is_project_page: false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
plugins:
- jekyll-remote-theme
