repository: tygerlord/tygerlord.github.io
remote_theme: pages-themes/slate@v0.2.0

title: Le blog du Tigre
title_en: The Tiger's Blog
description: Divers sujets techniques et philosophiques qui m'intéressent
description_en: Various technical and philosophical topics that interest me
lang: fr_FR
github:
  is_project_page: false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
plugins:
- jekyll-remote-theme

